### ISSUE TITLE
Some Factual errors in the GWU case study

### ISSUE THREAD

**Issue by nirabpudasaini** [osmlab/teachosm#43]
There are some factual errors in the case study (https://github.com/osmlab/teachosm/blob/gh-pages/_posts/en/casestudies/0900-11-12-gw-mapping.md) regarding Kathmandu Mapping work. It would be nice if those were corrected. 

1. "In fall 2014 they worked on another collaborative project in conjunction with USAID and the Open Cities Project at the World Bank.". 
The mapping work by GWU students in Kathmandu Valley took place in 2013 November. Take a look at this blog Post. http://gwtoday.gwu.edu/students-help-map-nepal%E2%80%99s-kathmandu .

2. "Field partners for this collaboration were a World Bank funded non-profit called Kathmandu Living Labs." 
This is only partly true. Kathmandu Living Labs was started as an extension of the World Bank's Open Cities project but is not funded by World Bank. Kathmandu Living Labs are involved in various other projects and OSM is a core part in all their works. Please check http://kathmandulivinglabs.org/project and http://kathmandulivinglabs.org/ for more information regarding Kathmandu Living Labs.

3."They performed field validation on the data created by the students and collected additional attribute information for critical infrastructure in the city (schools and hospitals)."

The School and Hospital data creation was a bigger project and the details regarding it can be found at http://kathmandulivinglabs.org/project/details/23. Apart from the field coordination of the remote mapping session Kathmandu Living Labs ran OSM Patrol Sessions (Data Quality check and Validation) of OSM data for whole Kathmandu.  

I would request you to make changes if possible. 

Regards
Nirab

**Comment by rhinton17** [comment]
Corrections made to case study
