### ISSUE TITLE
investigate options for fulfilling "service learning" requirements

### ISSUE THREAD

**Issue by mikelmaron** [osmlab/teachosm#44]
* what documentation is required to fulfill "service learning" requirements at high school level?
* what does it take to have a "citizen science" "certification"? some concern about what certification means in detail (how onerous?). FCPCCS may have insights.
* badges could be a lightweight options.

**Comment by geomantic** [comment]
+ Investigating a geo-badge process with Jon Merino/MapStory 
+ Review FCPCCS materials
+ Public schools (notably DC) require organizations to have 501(c)3 status in order to grant credit for student involvement

**Comment by geomantic** [comment]
Vince Denoto, Director of Natl Sci Foundation GeoTech Ctr has asked for a proposal for a microcredential based on using OpenStreetMap.

**Comment by geomantic** [comment]
Closing this. Issue is OBE because...GeoBadges.
