### ISSUE TITLE
review Missing Maps school project materials

### ISSUE THREAD

**Issue by mikelmaron** [osmlab/teachosm#73]
https://drive.google.com/drive/u/0/#folders/0B_hW0KstPK1AY0t5M2c0TVhFamc/0B_oUuPnytdlEWUtLOHhjYVR1Umc/0B_oUuPnytdlEaXpZTHRhdDhXZGM

may be some useful pieces to use, people to connect with

status of the program is unknown

**Comment by geomantic** [comment]
@mikel I've reviewed the materials and there are a few gems we can look at, particularly the pieces that consider outreach to schools/educ institutions. Besides Pete, do you know any of the others?

**Comment by mikelmaron** [comment]
Pete would be the main person to connect with on this ... need his contact?


     On Friday, October 23, 2015 12:12 PM, Steven Johnson <notifications@github.com> wrote:
   
 

 @mikel I've reviewed the materials and there are a few gems we can look at, particularly the pieces that consider outreach to schools/educ institutions. Besides Pete, do you know any of the others?—

**Comment by geomantic** [comment]
OBE
