### ISSUE TITLE
Duplicate instead of fork from learnosm?

### ISSUE THREAD

**Issue by bgirardot** [osmlab/teachosm#75]
Am I the only person who has a problem because as a fork of learnosm, I can not fork this repo for local development and pull requests without it affecting my github fork of learnosm?

Basically since I have a fork of learnosm, if I fork this repo it just get treated as an out of sync branch of my learnosm repo, it does not create a new repo for me in my github account. Actually, I am not sure it creates a new branch, I think it makes my learnosm gh-pages branch 100's of commits behind learnosm.

Any advice in how to deal with that would be much appreciated.

**Comment by mikelmaron** [comment]
Makes sense to break the tie to learnosm. It was a good starting point to fork from, but that's all. What's the easiest way to do this?

**Comment by geomantic** [comment]
I have no idea where to begin, but agree that now is the time to do it while the overhead to the TeachOSM project is relatively low. I'd be willing to put some energy to sorting it out...if given some direction.

**Comment by bgirardot** [comment]
I'll see if I can find some advice or suggestions on it.

**Comment by bgirardot** [comment]
I found this question and answer about this issue:
http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

**Comment by mikelmaron** [comment]
I'm contacting GitHub support now

**Comment by bgirardot** [comment]
Oh cool. thank you very much, this will make it much easier for me to contribute, I am not a git/github expert (or even average) user so I got stopped in my tracks when forking this and it just disappearing in to and affecting my learnosm repo.

**Comment by mikelmaron** [comment]
and we're datached
