### ISSUE TITLE
Improve visibility of "Why Teach.." link on homepage

### ISSUE THREAD

**Issue by geobrando** [osmlab/teachosm#77]
Checked out teachosm.org for the first time when sending the link to someone that's used a non-OSM mapping platform to teach young people.  I was looking for information on the advantages of using OSM but the link to http://teachosm.org/en/intro/whyteach/ wasn't easily discernible on the homepage and I only happened upon it using the site navigation box on other pages.

In my opinion, it could be made more clear that the banner image links to ```/whyteach``` outside of the "hand on the door" image that changes.  I'm not a UI guy but perhaps the image could change in some way after hover. It also might help to change the "Why Teach OSM In The Classroom" text as it gets a bit lost against the monochrome image and the white page background.

**Comment by mikelmaron** [comment]
Thanks, good feedback. I think the changing opacity on hover over the banner image could be just the thing. * Mikel Maron * +14152835207 @mikel s:mikelmaron 

     On Sunday, February 22, 2015 4:19 PM, Brandon Knight <notifications@github.com> wrote:
   
 

 Checked out teachosm.org for the first time when sending the link to someone that's used a non-OSM mapping platform to teach young people. I was looking for information on the advantages of using OSM but the link to http://teachosm.org/en/intro/whyteach/ wasn't easily discernible on the homepage and I only happened upon it using the site navigation box on other pages.In my opinion, it could be made more clear that the banner image links to /whyteach outside of the "hand on the door" image that changes. I'm not a UI guy but perhaps the image could change in some way after hover. It also might help to change the "Why Teach OSM In The Classroom" text as it gets a bit lost against the monochrome image and the white page background.—
